import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { AuroraBackground } from '@/components/ui/aurora-background';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Chethan | Portfolio-Site',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title as string}</title>
        <meta name="description" content={metadata.description as string} />
      </head>
      <body className={`${inter.className} bg-black`}>
        <AuroraBackground>{children}</AuroraBackground>
      </body>
    </html>
  );
}
